# 7-7. [Boxplot Demo](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.boxplot.html#matplotlib.axes.Axes.boxplot)

In [10]:
import matplotlib.pyplot as plt

from matplotlib.axes import Axes
from matplotlib.patches import Circle
from matplotlib.patheffects import withStroke
from matplotlib.transforms import Affine2D

import pandas as pd
import numpy as np
import inspect

In [2]:
def circle(ax, x, y, radius=0.15):
    from matplotlib.patches import Circle
    from matplotlib.patheffects import withStroke
    circle = Circle((x, y), radius, clip_on=False, zorder=10, linewidth=1,
                    edgecolor='black', facecolor=(0, 0, 0, .0125),
                    path_effects=[withStroke(linewidth=5, foreground='w')])
    ax.add_artist(circle)


def text(ax, x, y, text):
    ax.text(x, y, text, backgroundcolor="white",
            ha='center', va='top', weight='bold', color='blue')

In [3]:
%matplotlib widget

introspect : 反思，内省，内观
annotation : 注解，注释

## API [Axes.boxplot](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.boxplot.html#matplotlib.axes.Axes.boxplot)

箱线图与其它基本图形一样在matplotlib中是由Axes类的辅助方法boxplot绘制的。

In [6]:
str(inspect.signature(Axes.boxplot))

'(self, x, notch=None, sym=None, vert=None, whis=None, positions=None, widths=None, patch_artist=None, bootstrap=None, usermedians=None, conf_intervals=None, meanline=None, showmeans=None, showcaps=None, showbox=None, showfliers=None, boxprops=None, labels=None, flierprops=None, medianprops=None, meanprops=None, capprops=None, whiskerprops=None, manage_ticks=True, autorange=False, zorder=None, *, data=None)'

观察其签名，只有参数x是必选的。而参数x的输入可以是一个数组，也可以是一个向量序列。

## 准备数据

In [4]:
# Fixing random state for reproducibility
np.random.seed(19680801)

In [5]:
# fake up some data
spread = np.random.rand(50) * 100
center = np.ones(25) * 50
flier_high = np.random.rand(10) * 100 + 100
flier_low = np.random.rand(10) * -100
data = np.concatenate((spread, center, flier_high, flier_low))

## 最简用例

In [6]:
fig1, ax1 = plt.subplots()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [7]:
ax1.boxplot(data)

{'whiskers': [<matplotlib.lines.Line2D at 0x8b937f0>,
 'caps': [<matplotlib.lines.Line2D at 0x8b71850>,
 'boxes': [<matplotlib.lines.Line2D at 0x8b93930>],
 'medians': [<matplotlib.lines.Line2D at 0x878c430>],
 'fliers': [<matplotlib.lines.Line2D at 0x878c490>],
 'means': []}

想法：

1. 制作好的图表应该加上注释，话句话说将描述性文本添加到图中。计划的流程是先写描述性文档，之后将文档添加到图中。
2. api的结构图，python中有库pycallgraph

- PyQtGraph
- Plotly Express

从示例 [Anatomy of a figure](https://matplotlib.org/gallery/showcase/anatomy.html#sphx-glr-gallery-showcase-anatomy-py) 得到在图中画圈标注的启示，可要将画圈标注方法用在写作实践中却遇到了一个经典的问题，如何将圆画圆？  
散点图是如何做到的？

我猜，应该是将数据坐标转换的顶点转换成轴坐标，已轴坐标画标记。

In [10]:
circle(ax1, 0.5, 50)

In [21]:
trans = ax1.transData.transform((0.5, 50))

In [22]:
trans

array([100.        , 296.56831646])

In [17]:
ax1.transAxes.transform_point((0.5,0.5))

array([410., 297.])

In [20]:
ax1.transAxes.inverted()

In [26]:
(ax1.transData + ax1.transAxes.inverted()).transform([0.7, 50])

array([0.2       , 0.49906562])

In [12]:
reduction = 1

In [20]:
circle = Circle([1000       , 5000], 100, clip_on=False, zorder=10, linewidth=1,
                    edgecolor='black', facecolor=(0, 0, 0, .0125),
                    transform=Affine2D().scale(0.5 * reduction),
                    path_effects=[withStroke(linewidth=5, foreground='w')])
ax1.add_artist(circle)